name: "Run standard with reviewdog"
description: "🐶 Run Standard Ruby and Standard Rails with reviewdog on pull requests to improve code review experience."
author: "mgrachev (reviewdog)"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  standard_options:
    description: "standard options. (standardrb <standard_options>)"
    default: "--format progress"
  tool_name:
    description: "Tool name to use for reviewdog reporter"
    default: "standard"
  level:
    description: "Report level for reviewdog [info,warning,error]"
    default: "error"
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-review.
    default: "github-pr-review"
  standard_version:
    description: "Standard Ruby version"
  standard_rails_version:
    description: "Standard Rails version"
  files:
    description: "Files to lint [default: ./]"
    default: "./"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `true`.
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.standard_options }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.standard_version }}
    - ${{ inputs.standard_rails_version }}
    - ${{ inputs.files }}
branding:
  icon: "check-circle"
  color: "red"
