name: SemVer
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: haya14busa/action-update-semver@v1
        with:
          github_token: ${{ secrets.github_token }}
